name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installa dipendenze
        run: npm install

      - name: Build (se necessario)
        run: npm run build --if-present

      - name: Avvia server (in background)
        run: |
          npm start &
          npx wait-on http://localhost:4200

      - name: Esegui Cypress
        run: npm run cy:run
